import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Supabase notes App",
  description: "Generated by ajay kumar sharma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.container}>
        {children}
      </body>
    </html>
  );
}
